### ISSUE TITLE
NoneType object has no attribute 'copy'

### ISSUE THREAD

**Issue by tirthadagr8** [DSCKGEC/OCR-TextRecognition#5]
https://github.com/DSCKGEC/OCR-TextRecognition/blob/4cc8f97aaf1e4a67b88e46d20a5f9821101fa678/OCR/OCRTextRecg.py#L50
Fixing other issues must resolve it

**Comment by Abhilash1781** [comment]
tirthadagr8 please assign this issue to me  , i will resolve it

**Comment by Abhilash1781** [comment]
tirthadagr8 i have messaged you in discord regarding few doubts . Please go through it

**Comment by tirthadagr8** [comment]
Just write what should be the right statement with reference to the wrong one.

**Comment by Abhilash1781** [comment]
This error occured due to not providing the file path or invalid file path given to cv2.imread function . Actually cv2.imread does not explicitely throws an error that given path is invalid instead it will return None.
There's a line in OCRTextRecg.py file --> image = cv2.imread(args["image"]) . If you clearly observe there's a variable called "args" . This variable contains all arguments which is need to be parsed. 
This is one of the argument in the args variable.
 ap.add_argument("-i", "--image", type=str,
	help="path to input image") 
The above two lines requests user to provide a file path to the image . 

ap.add_argument("-east", "--east", type=str,
	help="path to input EAST text detector")
This requests user to provide the file path of east text detector


**TYPE 1 OF RUNNING THIS PYTHON FILE**
We will typically click on 'RUN' option to run this script , it tries to get the file path , error occurs

**HOW WE NEED TO RUN THIS SCRIPT**
1)Open the working directory of file in command prompt
2) enter python OCRTextRecg.py  -i=complete file path of the image    -east=complete file path of East text detector
for example : OCRTextRecg.py -i=C:\Users\Dell\Desktop\tess\image.jpg    
         -east=C:\Users\Dell\Desktop\tess\frozen_east_test_detection.pb

**Comment by tirthadagr8** [comment]
Nicely done. You can give push request
